### ISSUE TITLE
unexpected EOF problem

### ISSUE THREAD

**Issue by chenjun2hao** [yxlijun/DSFD.pytorch#2]
hi, thanks your excellent job, I meet the error:
```
Traceback (most recent call last):
  File "/media/chenjun/ed/30_face/detect/DSFD.pytorch/demo.py", line 107, in <module>
    net.load_state_dict(torch.load(args.model))
  File "/home/chenjun/miniconda2/envs/test/lib/python3.6/site-packages/torch/serialization.py", line 261, in load
    return _load(f, map_location, pickle_module)
  File "/home/chenjun/miniconda2/envs/test/lib/python3.6/site-packages/torch/serialization.py", line 416, in _load
    deserialized_objects[key]._set_from_file(f, offset)
RuntimeError: unexpected EOF. The file might be corrupted
```

when i use the pretrained model.so, could you please raplace the pretrained model, thanks.

**Comment by yxlijun** [comment]
I have replace the pretrained model,you can try again
