### ISSUE TITLE
python demo.py ModuleNotFoundError: No module named 'detection'

### ISSUE THREAD

**Issue by ChauncyFr** [yxlijun/DSFD.pytorch#20]
when i run demo.py ,its always got 

```
Traceback (most recent call last):
  File "demo.py", line 21, in <module>
    from models.factory import build_net
  File "/home/fxru/tensorflow_learn/DSFD.pytorch-master/models/factory.py", line 9, in <module>
    from .DSFD_vgg import build_net_vgg
  File "/home/fxru/tensorflow_learn/DSFD.pytorch-master/models/DSFD_vgg.py", line 16, in <module>
    from layers import *
  File "/home/fxru/tensorflow_learn/DSFD.pytorch-master/layers/__init__.py", line 8, in <module>
    from .functions import *
  File "/home/fxru/tensorflow_learn/DSFD.pytorch-master/layers/functions/__init__.py", line 2, in <module>
    from detection import Detect
ModuleNotFoundError: No module named 'detection'

```

**Comment by chenwuxing** [comment]
you can add '.' before detection,like this 'from .detection import Detect
