### ISSUE TITLE
resnet50  IndexError: index 750 is out of range for dimension 0

### ISSUE THREAD

**Issue by ChauncyFr** [yxlijun/DSFD.pytorch#21]
First, I used resnet50 to train and got the training result dsfd.pth model, but when I used the model to infer in demo.py, I got the following error:

```
Traceback (most recent call last):
  File "demo1.py", line 134, in <module>
    detect(net, path, args.thresh, f)
  File "demo1.py", line 89, in detect
    while detections[0, i, j, 0] >= thresh:
IndexError: index 750 is out of range for dimension 0 (of size 750)

```

**Comment by GaoXinJian-USTC** [comment]
hello, have you solve this problem?
