### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by fuchao01** [yxlijun/DSFD.pytorch#7]
Traceback (most recent call last):
  File "train.py", line 257, in <module>
    train()
  File "train.py", line 117, in train
    base_weights = torch.load(args.save_folder + basenet)
  File "/usr/lib64/python2.7/site-packages/torch/serialization.py", line 265, in load
    f = open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'weights/vgg16_reducedfc.pth'

**Comment by ltcs11** [comment]
try to download the basenet checkpoint in readme "I use basenet **vgg** to train DSFD"

**Comment by testingshanu** [comment]
Hey,
May I know the number of epochs that was used in the VGG based DSFD model that was trained?
